#page title
page_title                                : Mobile Lucida                                      # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.arlucida.mobilelucida   # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Mobile Lucida                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : $4.99                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Fall in love with drawing again.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Vincent Moeykens
your_link                                 : https://mobilelucida.com
your_city                                 : Burlington, Vermont
email_address                             : support@arlucida.com
facebook_username                         :
instagram_username                        : mobilelucida
twitter_username                          : mobilelucida
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Draw Beautiful Pictures
    description                           : No experience required; if you can trace, you can draw! Mobile Lucida lowers the entry bar for becoming an artist.
    fontawesome_icon_name                 : magic

  - title                                 : Get Proportions Perfect
    description                           : If you're an experienced artist, Mobile Lucida is for you too! Have trouble with getting your starting proportions correct? AR Lucida helps you nail them every time.
    fontawesome_icon_name                 : mobile

  - title                                 : Filters For Every Piece
    description                           : Whether it is edge detecting, posterizing, or breaking down the color pallette, Mobile Lucida has filters to help you on every project!
    fontawesome_icon_name                 : play-circle

  - title                                 : Draw Like the Masters
    description                           : Camera Obscura devices have been used for centuries by artists (even Vermeer used one!). Mobile Lucida implements this same idea but utilizing modern technology!
    fontawesome_icon_name                 : sync

#  - title                                 : Easy to Tweak
#    description                           : Tweak accent color, images, icons and transparency via the _config.yml file. No HTML/CSS needed.
#    fontawesome_icon_name                 : adjust
#
#  - title                                 : Feature List
#    description                           : Add features (like this one) to your site via the _config.yml file. No HTML/CSS needed.
#    fontawesome_icon_name                 : star
#
#  - title                                 : Smart App Banner
#    description                           : Display a smart app banner on iOS devices.
#    fontawesome_icon_name                 : arrow-alt-circle-down
#
#  - title                                 : Social Links
#    description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
#    fontawesome_icon_name                 : link
#
#  - title                                 : FontAwesome Support
#    description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
#    fontawesome_icon_name                 : info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#3F51B5"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
